DROP TABLE IF EXISTS urls;

CREATE TABLE urls(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
    original_url TEXT NOT NULL ,
    clicks  INTEGER NOT NULL DEFAULT 0
);
